# Тема №10. Декораторы и исключения

Отчет по Теме №10 выполнил:

- Голосов Михаил Кириллович
  
- ОЗИВТ-22-1-у
  
| Задание | Лаб_Раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:

- к.э.н, доцент Панов М.А

# Лабороторная работа№1
### Наверняка вы думаете, что декораторы – это какая-то бесполезная вещь, которая вам никогда не пригодится, но тут вдруг на паре по математике преподаватель просит всех посчитать число Фибоначчи для 100. Кто-то будет считать вручную (так точно не нужно), кто-то посчитает на калькуляторе, а кто-то подумает, что он самый крутой и напишет рекурсивную программу на Python и немного огорчится, потому что данная программа будет достаточно долго считаться, если ее просто так запускать. Но именно тут к вам на помощь приходят декораторы, например @lru_cache (он предназначен для решения задач динамическим программированием, если простыми словами, то этот декоратор запоминает промежуточные результаты и при рекурсивном вызове функции программа не будет считать одни и те же значения, а просто “возьмёт их из этого декоратора”). Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи. 
P.S. при запуске без декоратора можете долго не ждать, для наглядности хватит 10 секунд ожидания. 
```python
import time
from functools import lru_cache

# Декоратор @lru_cache используется для кэширования результатов вызовов функции fib.
@lru_cache(maxsize=None)
def fib(n):
    if n <= 1:
        return n
    else:
        return fib(n-1) + fib(n-2)

# Засекаем время начала выполнения программы без использования декоратора.
start_time_without_cache = time.time()

# Вызываем функцию fib для числа Фибоначчи 100 без использования кэша.
result_without_cache = fib(100)

# Засекаем время окончания выполнения программы без использования декоратора.
end_time_without_cache = time.time()

# Выводим результат и время выполнения без использования декоратора.
print(f"Результат без кэша: {result_without_cache}")
print(f"Время выполнения без кэша: {end_time_without_cache - start_time_without_cache} сек.")

# Засекаем время начала выполнения программы с использованием декоратора.
start_time_with_cache = time.time()

# Вызываем функцию fib для числа Фибоначчи 100 с использованием кэша.
result_with_cache = fib(100)

# Засекаем время окончания выполнения программы с использованием декоратора.
end_time_with_cache = time.time()

# Выводим результат и время выполнения с использованием декоратора.
print(f"Результат с кэшем: {result_with_cache}")
print(f"Время выполнения с кэшем: {end_time_with_cache - start_time_with_cache} сек.")
```
### Результат
![Меню](https://github.com/Dardners/python-programming/blob/main/picture/Theme_10-1.png)
## Выводы
1. import time - Импорт модуля time для измерения времени выполнения программы.
2. from functools import lru_cache - Импорт декоратора lru_cache из модуля functools.
3. @lru_cache(maxsize=None) - Применение декоратора lru_cache к функции fib с максимальным размером кэша (None означает неограниченный кэш).
4. def fib(n): - Определение функции fib для вычисления числа Фибоначчи.
5. if n <= 1: - Базовый случай рекурсии: если n меньше или равно 1, возвращаем n.
6. return fib(n-1) + fib(n-2) - Рекурсивный случай: возвращаем сумму двух предыдущих чисел Фибоначчи.
7. start_time_without_cache = time.time() - Засекаем время начала выполнения программы без использования кэша.
8. result_without_cache = fib(100) - Вызываем функцию для числа Фибоначчи 100 без использования кэша.
9. end_time_without_cache = time.time() - Засекаем время окончания выполнения программы без использования кэша.
10. Выводим результат и время выполнения без использования кэша.
11. start_time_with_cache = time.time() - Засекаем время начала выполнения программы с использованием кэша.
12. result_with_cache = fib(100) - Вызываем функцию для числа Фибоначчи 100 с использованием кэша.
13. end_time_with_cache = time.time() - Засекаем время окончания выполнения программы с использованием кэша.
14. Выводим результат и время выполнения с использованием кэша.

# Лабороторная работа№2
### Илья пишет свой сайт и ему необходимо сделать минимальную проверку ввода данных пользователя при регистрации. Для этого он реализовал функцию, которая выводит данные пользователя на экран и решил, что будет проверять правильность введённых данных при помощи декоратора, но в этом ему потребовалась ваша помощь. Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130. 
Причем заметьте, что неважно сколько пользователь введет данных на сайт к Илье, будут обрабатываться только первые 2 аргумента. 
```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]
        if age < 0 or age > 130:
            age = 'Недопустимый возраст'
        input_func(name, age)
    return output_func
@check
def personal_info(name, age):
    print(f"Name: {name} Age {age}")
if __name__ == '__main__':
    personal_info('Михаил', 38)
    personal_info('Александр', -5)
    personal_info('Виктор', 138, 15, 48, 2)
```
### Результат
![Меню](https://github.com/Dardners/python-programming/blob/main/picture/Theme_10-2.png)
## Выводы
1. def check(input_func): - Определение декоратора check, который принимает функцию input_func.
2. def output_func(*args): - Определение внутренней функции output_func, принимающей произвольное количество аргументов.
3. name, age = args[0], args[1] - Извлечение значений name и age из переданных аргументов.
4. if age < 0 or age > 130: - Проверка условия: если возраст меньше 0 или больше 130.
5. age = 'Недопустимый возраст' - Присвоение переменной age строки 'Недопустимый возраст', если условие выполнено.
6. input_func(name, age) - Вызов исходной функции input_func с переданными аргументами name и age.
7. return output_func - Возвращение функции output_func как результата декоратора.
8. @check - Применение декоратора check к функции personal_info.
9. if __name__ == '__main__': - Проверка, является ли скрипт основным (не импортированным).
10. personal_info('Михаил', 38) - Вызов функции personal_info с аргументами 'Михаил' и 38.
11. personal_info('Александр', -5) - Вызов функции personal_info с аргументами 'Александр' и -5.
12. personal_info('Виктор', 138, 15, 48, 2) - Вызов функции personal_info с аргументами 'Виктор', 138, 15, 48, 2 (декоратор применяется только к первым двум аргументам).

# Лабороторная работа№3
### Вам понравилась идея Ильи с сайтом, и вы решили дальше работать вместе с ним. Но вот в вашем проекте появилась проблема, кто-то пытается сломать вашу функцию с получением данных для сайта. Эта функция работает только с данными integer, а какой-то недохакер пытается все сломать и вместо нужного типа данных отправляет string. Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт. Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена.
```python
def get_user_data(name, age):
    try:
        # Попытка выполнить следующий блок кода

        age = int(age)
        # Преобразование переменной age в целочисленный тип

        if age < 0 or age > 130:
            # Проверка условия: если возраст меньше 0 или больше 130

            raise ValueError("Недопустимый возраст")
            # Вызов исключения ValueError с сообщением

        print(f"Получены данные: Имя: {name}, Возраст: {age}")
        # Вывод информации о полученных данных

    except ValueError as e:
        # Обработка исключения ValueError (неправильный тип данных)

        print(f"Ошибка: {e}")
        # Вывод сообщения об ошибке

    except Exception as e:
        # Обработка общего исключения (если произойдет любая другая ошибка)

        print(f"Произошла ошибка: {e}")

    finally:
        # Блок кода, который будет выполнен в любом случае (например, для очистки ресурсов)

        print("Конец выполнения функции")

# Пример использования функции:
if __name__ == '__main__':
    get_user_data('Михаил', 38)
    get_user_data('Александр', 'abc')  # Передача строки вместо числа
    get_user_data('Виктор', 150)
```
### Результат
![Меню](https://github.com/Dardners/python-programming/blob/main/picture/Theme_10-3.png)
## Выводы
1. try: - Блок кода, который пытается выполниться.
2. age = int(age) - Преобразование переменной age в целочисленный тип. Если введенное значение невозможно преобразовать в целое число, возникнет исключение.
3. if age < 0 or age > 130: - Проверка условия на допустимость возраста.
4. raise ValueError("Недопустимый возраст") - Возбуждение исключения ValueError с сообщением "Недопустимый возраст".
5. print(f"Получены данные: Имя: {name}, Возраст: {age}") - Вывод информации о полученных данных.
6. except ValueError as e: - Обработка исключения ValueError. Вывод сообщения об ошибке.
7. except Exception as e: - Обработка общего исключения. Вывод сообщения об ошибке.
8. finally: - Блок кода, который будет выполнен в любом случае (например, для очистки ресурсов).
9. print("Конец выполнения функции") - Вывод сообщения о завершении выполнения функции.
10. Пример использования функции с разными значениями аргументов для демонстрации обработки различных сценариев.

# Лабороторная работа№4
### Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться “Успешная регистрация”.
```python
class NameTooLongError(Exception):
    # Определение собственного исключения NameTooLongError, которое наследуется от базового класса Exception
    pass

def register_user(name):
    try:
        # Попытка выполнить следующий блок кода

        if len(name) > 10:
            # Проверка длины имени, если длина превышает 10 символов

            raise NameTooLongError("Имя слишком длинное")
            # Вызов собственного исключения с сообщением "Имя слишком длинное"

        print("Успешная регистрация")
        # Вывод сообщения об успешной регистрации

    except NameTooLongError as e:
        # Обработка собственного исключения NameTooLongError

        print(f"Ошибка: {e}")
        # Вывод сообщения об ошибке

    except Exception as e:
        # Обработка общего исключения (если произойдет любая другая ошибка)

        print(f"Произошла ошибка: {e}")

    finally:
        # Блок кода, который будет выполнен в любом случае (например, для очистки ресурсов)

        print("Завершение функции")

# Пример использования функции:
if __name__ == '__main__':
    register_user('John')     # Успешная регистрация
    register_user('SuperLongName')  # Вызов собственного исключения NameTooLongError
```
### Результат
![Меню](https://github.com/Dardners/python-programming/blob/main/picture/Theme_10-4.png)
## Выводы
1. class NameTooLongError(Exception): - Определение собственного исключения NameTooLongError, которое наследуется от базового класса Exception.
2. try: - Блок кода, который пытается выполниться.
3. if len(name) > 10: - Проверка длины имени, если она превышает 10 символов.
4. raise NameTooLongError("Имя слишком длинное") - Вызов собственного исключения NameTooLongError с сообщением "Имя слишком длинное".
5. print("Успешная регистрация") - Вывод сообщения об успешной регистрации.
6. except NameTooLongError as e: - Обработка собственного исключения NameTooLongError.
7. print(f"Ошибка: {e}") - Вывод сообщения об ошибке.
8. except Exception as e: - Обработка общего исключения (если произойдет любая другая ошибка).
9. print(f"Произошла ошибка: {e}") - Вывод сообщения об ошибке.
10. finally: - Блок кода, который будет выполнен в любом случае (например, для очистки ресурсов).
11. print("Завершение функции") - Вывод сообщения о завершении выполнения функции.
12. Пример использования функции с разными значениями аргументов для демонстрации обработки различных сценариев.

# Лабороторная работа№5
### После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: __init__() (вызывается при создании класса декоратора в программе) и __call__() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль. 
```python
class SimpleLoggerDecorator:
    # Определение класса декоратора

    def __init__(self, func):
        # Метод, вызываемый при создании экземпляра класса декоратора

        self.func = func
        # Сохранение переданной функции для дальнейшего вызова

    def __call__(self, *args, **kwargs):
        # Метод, вызываемый при вызове декоратора

        print(f"Лог: Вызвана функция {self.func.__name__} с аргументами {args} и ключевыми аргументами {kwargs}")
        # Вывод лога с информацией о вызове функции и переданных аргументах

        result = self.func(*args, **kwargs)
        # Вызов оригинальной функции с переданными аргументами

        print(f"Лог: Функция {self.func.__name__} выполнена, результат: {result}")
        # Вывод лога с информацией о завершении выполнения функции и результате

        return result
        # Возвращение результата выполнения оригинальной функции

@SimpleLoggerDecorator
def example_function(x, y):
    # Пример функции, к которой применен декоратор

    return x + y

# Пример использования декорированной функции:
if __name__ == '__main__':
    result = example_function(3, 5)
    # Вызов декорированной функции с аргументами 3 и 5

    print(f"Итоговый результат: {result}")
    # Вывод итогового результата выполнения функции
```
### Результат
![Меню](https://github.com/Dardners/python-programming/blob/main/picture/Theme_10-5.png)
## Выводы 
1. class SimpleLoggerDecorator: - Определение класса декоратора.
2. def __init__(self, func): - Метод, вызываемый при создании экземпляра класса декоратора. Сохраняет переданную функцию для дальнейшего вызова.
3. self.func = func - Сохранение переданной функции в атрибуте func.
4. def __call__(self, *args, **kwargs): - Метод, вызываемый при вызове декоратора.
5. print(f"Лог: Вызвана функция {self.func.__name__} с аргументами {args} и ключевыми аргументами {kwargs}") - Вывод лога с информацией о вызове функции и переданных аргументах.
6. result = self.func(*args, **kwargs) - Вызов оригинальной функции с переданными аргументами и сохранение результата.
7. print(f"Лог: Функция {self.func.__name__} выполнена, результат: {result}") - Вывод лога с информацией о завершении выполнения функции и результате.
8. return result - Возвращение результата выполнения оригинальной функции.
9. @SimpleLoggerDecorator - Применение декоратора к функции example_function.
10. def example_function(x, y): - Пример функции, к которой применен декоратор.
11. return x + y - Возвращение суммы аргументов.
12. result = example_function(3, 5) - Вызов декорированной функции с аргументами 3 и 5.
13. print(f"Итоговый результат: {result}") - Вывод итогового результата выполнения функции.

# Самостоятельная работа№1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор. 
Подсказка: необходимо использовать модуль time Декоратор необходимо использовать для этой функции: 
def fibonacci(): fib1 = fib2= 1 
for i inrange(2, 200): fib1,fib2= fib2,fib1 + fib2 print(fib2,end=' ') 
if__name__ == '__main__': fibonacci() 
Результатом вашей работы будет листинг кода и скриншот консоли, в котором будет выполненная функция Фибоначчи и время выполнения программы. 
Также на этом примере можете посмотреть, что решение задач через рекурсию не всегда является хорошей идеей. Поскольку решение Фибоначчи для 100 с использованием рекурсии и без динамического программирования решается более десяти секунд, а решение точно такой же задачи, но через цикл for еще и для 200, занимает меньше 1 секунды. 
```python
import time

def timing_decorator(func):
    # Определение декоратора для измерения времени выполнения функции

    def wrapper(*args, **kwargs):
        # Внутренняя функция-обертка

        start_time = time.time()
        # Запоминание текущего времени перед выполнением функции

        result = func(*args, **kwargs)
        # Вызов исходной функции с переданными аргументами

        end_time = time.time()
        # Запоминание текущего времени после выполнения функции

        elapsed_time = end_time - start_time
        # Вычисление затраченного времени

        print(f"Время выполнения функции {func.__name__}: {elapsed_time} секунд")
        # Вывод информации о времени выполнения функции

        return result
        # Возвращение результата выполнения исходной функции

    return wrapper
    # Возвращение функции-обертки как результата декоратора

@timing_decorator
def fibonacci():
    # Функция, для которой применяется декоратор
    fib1, fib2 = 1, 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```
### Результат
![Меню](https://github.com/Dardners/python-programming/blob/main/picture/Theme_10-6.png)
## Выводы
1. import time - Импорт модуля time для работы с временем.
2. def timing_decorator(func): - Определение декоратора timing_decorator, принимающего функцию func.
3. def wrapper(*args, **kwargs): - Определение внутренней функции-обертки wrapper, принимающей произвольное количество позиционных и именованных аргументов.
4. start_time = time.time() - Запоминание текущего времени перед выполнением функции.
5. result = func(*args, **kwargs) - Вызов исходной функции с переданными аргументами.
6. end_time = time.time() - Запоминание текущего времени после выполнения функции.
7. elapsed_time = end_time - start_time - Вычисление затраченного времени.
8. print(f"Время выполнения функции {func.__name__}: {elapsed_time} секунд") - Вывод информации о времени выполнения функции.
9. return result - Возвращение результата выполнения исходной функции.
10. @timing_decorator - Применение декоратора timing_decorator к функции fibonacci.
11. def fibonacci(): - Определение функции fibonacci, для которой применяется декоратор.
12. fib1, fib2 = 1, 1 - Инициализация переменных для последовательности Фибоначчи.
13. for i in range(2, 200): - Цикл для генерации последовательности Фибоначчи.
14. print(fib2, end=' ') - Вывод элемента последовательности Фибоначчи.
15. if __name__ == '__main__': - Проверка, является ли скрипт основным (а не импортированным).
16. fibonacci() - Вызов функции fibonacci с применением декоратора для измерения времени выполнения.

# Самостоятельная работа№2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла. 
```python
try:
    # Попытка выполнить следующий блок кода

    # Проверка содержимого пустого файла
    with open('empty_file.txt', 'r') as empty_file:
        data = empty_file.read()
        if not data:
            raise Exception("Файл пустой")
        print("Содержимое пустого файла:", data)

    # Проверка содержимого файла с данными
    with open('non_empty_file.txt', 'r') as non_empty_file:
        data = non_empty_file.read()
        if not data:
            raise Exception("Файл пустой")
        print("Содержимое файла с данными:", data)

except FileNotFoundError:
    # Обработка исключения FileNotFoundError (если файл не найден)

    print("Файл не найден")

except Exception as e:
    # Обработка общего исключения

    print(f"Ошибка: {e}")
```
### Результат
![Меню](https://github.com/Dardners/python-programming/blob/main/picture/Theme_10-7.png)
## Выводы
1. try: - Блок кода, который пытается выполниться.
2. with open('empty_file.txt', 'r') as empty_file: - Открытие файла 'empty_file.txt' для чтения с использованием контекстного менеджера.
3. data = empty_file.read() - Считывание данных из файла.
4. if not data: - Проверка, является ли файл пустым.
5. raise Exception("Файл пустой") - Вызов исключения с сообщением "Файл пустой", если файл пустой.
6. print("Содержимое пустого файла:", data) - Вывод содержимого файла, если он не пустой.
7. with open('non_empty_file.txt', 'r') as non_empty_file: - Открытие файла 'non_empty_file.txt' для чтения.
8. data = non_empty_file.read() - Считывание данных из файла.
9. if not data: - Проверка, является ли файл пустым.
10. raise Exception("Файл пустой") - Вызов исключения с сообщением "Файл пустой", если файл пустой.
11. print("Содержимое файла с данными:", data) - Вывод содержимого файла с данными, если он не пустой.
12. except FileNotFoundError: - Обработка исключения FileNotFoundError (если файл не найден).
13. print("Файл не найден") - Вывод сообщения о том, что файл не найден.
14. except Exception as e: - Обработка общего исключения.
15. print(f"Ошибка: {e}") - Вывод сообщения об ошибке.

# Самостоятельная работа№3
### Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль 
```python
def add_two_and_user_input():
    try:
        # Попытка выполнить следующий блок кода

        user_input = input("Введите число: ")
        # Получение числа от пользователя в виде строки

        number = float(user_input)
        # Преобразование строки в число с плавающей точкой

        result = 2 + number
        # Вычисление суммы 2 и введенного числа

        print(f"Результат сложения: {result}")

    except ValueError:
        # Обработка исключения ValueError (неподходящий тип данных)

        print("Ошибка: Неподходящий тип данных. Ожидалось число.")

# Тесты
if __name__ == '__main__':
    # Позитивный тест: ввод корректного числа
    add_two_and_user_input()

    # Негативный тест: ввод строки вместо числа
    add_two_and_user_input()

    # Негативный тест: ввод другого неподходящего типа данных
    add_two_and_user_input()
```
### Результат
![Меню](https://github.com/Dardners/python-programming/blob/main/picture/Theme_10-8.png)
## Выводы
1. def add_two_and_user_input(): - Определение функции add_two_and_user_input.
2. try: - Блок кода, который пытается выполниться.
3. user_input = input("Введите число: ") - Получение числа от пользователя в виде строки.
4. number = float(user_input) - Преобразование строки в число с плавающей точкой.
5. result = 2 + number - Вычисление суммы 2 и введенного числа.
6. print(f"Результат сложения: {result}") - Вывод результата сложения.
7. except ValueError: - Обработка исключения ValueError (неподходящий тип данных).
8. print("Ошибка: Неподходящий тип данных. Ожидалось число.") - Вывод сообщения об ошибке при неправильном вводе.

# Самостоятельная работа№4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода. 
```python
def my_decorator(func):
    # Определение класса декоратора

    def wrapper(*args, **kwargs):
        # Определение внутренней функции-обертки

        print(f"Декорированная функция {func.__name__} вызвана с аргументами {args} и ключевыми аргументами {kwargs}")
        # Вывод информации о вызове декорированной функции с переданными аргументами

        result = func(*args, **kwargs)
        # Вызов исходной функции с переданными аргументами

        print(f"Результат выполнения функции {func.__name__}: {result}")
        # Вывод результата выполнения исходной функции

        return result
        # Возвращение результата выполнения исходной функции

    return wrapper
    # Возвращение функции-обертки как результата декоратора

@my_decorator
def add_numbers(a, b):
    # Пример функции, к которой применен декоратор

    return a + b

@my_decorator
def multiply_numbers(x, y):
    # Еще один пример функции, к которой применен декоратор

    return x * y

# Пример использования декорированных функций:
if __name__ == '__main__':
    result1 = add_numbers(3, 5)
    result2 = multiply_numbers(2, 4)
```
### Результат
![Меню](https://github.com/Dardners/python-programming/blob/main/picture/Theme_10-9.png)
## Выводы
1. def my_decorator(func): - Определение класса декоратора.
2. def wrapper(*args, **kwargs): - Определение внутренней функции-обертки.
3. print(f"Декорированная функция {func.__name__} вызвана с аргументами {args} и ключевыми аргументами {kwargs}") - Вывод информации о вызове декорированной функции с переданными аргументами.
4. result = func(*args, **kwargs) - Вызов исходной функции с переданными аргументами и сохранение результата.
5. print(f"Результат выполнения функции {func.__name__}: {result}") - Вывод результата выполнения исходной функции.
6. return result - Возвращение результата выполнения исходной функции.
7. return wrapper - Возвращение функции-обертки как результата декоратора.
8. @my_decorator - Применение декоратора my_decorator к функции add_numbers.
9. return a + b - Возвращение суммы двух аргументов.
10. @my_decorator - Применение декоратора my_decorator к функции multiply_numbers.
11. return x * y - Возвращение произведения двух аргументов.
12. result1 = add_numbers(3, 5) - Вызов декорированной функции add_numbers.
13. result2 = multiply_numbers(2, 4) - Вызов декорированной функции multiply_numbers.

# Самостоятельная работа№5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода. 
```python
class CustomError(Exception):
    # Определение собственного исключения CustomError, которое наследуется от базового класса Exception
    pass

def validate_positive_number(value):
    # Функция для проверки, что число положительное, иначе вызывает исключение CustomError

    if value <= 0:
        raise CustomError("Число должно быть положительным")

def process_data(data):
    # Функция для обработки данных, где вызывается исключение CustomError при обнаружении некорректных данных

    for value in data:
        try:
            validate_positive_number(value)
            # Проверка, что значение положительное, иначе вызов исключения CustomError

            print(f"Обработка значения: {value}")
            # Вывод обработанных данных

        except CustomError as e:
            # Обработка собственного исключения CustomError

            print(f"Ошибка: {e}")
            # Вывод сообщения об ошибке

# Пример использования исключения CustomError:
if __name__ == '__main__':
    try:
        # Попытка выполнить следующий блок кода

        data1 = [1, -2, 3, 0, 5]
        process_data(data1)
        # Вызов функции для обработки данных

        data2 = [-1, 2, 4, 6, -8]
        process_data(data2)
        # Вызов функции для обработки данных

    except Exception as e:
        # Обработка общего исключения (если произойдет любая другая ошибка)

        print(f"Произошла ошибка: {e}")
        # Вывод сообщения об ошибке
```
### Результат
![Меню](https://github.com/Dardners/python-programming/blob/main/picture/Theme_10-10.png)
## Выводы
1. class CustomError(Exception): - Определение собственного исключения CustomError, которое наследуется от базового класса Exception.
2. def validate_positive_number(value): - Определение функции для проверки, что число положительное, иначе вызывает исключение CustomError.
3. if value <= 0: - Проверка, что значение положительное.
4. raise CustomError("Число должно быть положительным") - Вызов исключения CustomError с сообщением "Число должно быть положительным", если число не положительное.
5. def process_data(data): - Определение функции для обработки данных, где вызывается исключение CustomError при обнаружении некорректных данных.
6. for value in data: - Цикл для перебора значений в данных.
7. validate_positive_number(value) - Вызов функции для проверки, что значение положительное, иначе вызывается исключение CustomError.
8. print(f"Обработка значения: {value}") - Вывод обработанных данных.
9. except CustomError as e: - Обработка собственного исключения CustomError.
10. print(f"Ошибка: {e}") - Вывод сообщения об ошибке.
11. if __name__ == '__main__': - Проверка, является ли скрипт основным (а не импортированным).
12. data1 = [1, -2, 3, 0, 5] - Инициализация данных для первого теста.
13. process_data(data1) - Вызов функции для обработки данных.
14. data2 = [-1, 2, 4, 6, -8] - Инициализация данных для второго теста.
15. process_data(data2) - Вызов функции для обработки данных.
16. except Exception as e: - Обработка общего исключения (если произойдет любая другая ошибка).
17. print(f"Произошла ошибка: {e}") - Вывод сообщения об ошибке.

## Общий вывод
В этой работе были рассмотрены два важных аспекта программирования на Python: декораторы и исключения.
Использование декораторов и исключений в языке Python способствует созданию более гибкого и эффективного кода, делая программы устойчивыми к ошибкам и более легко поддерживаемыми.
